#ifndef DW_FS_ERR_H
#define DW_FS_ERR_H

#define ERR_NON_UNIQUE_NAME 111
#define ERR_NOT_EXISTS 112
#define ERR_OOM 113
#define ERR_PTR_NOT_ALLOCATED 114
#define ERR_FILE_NOT_OPEN 211

#endif //DW_FS_ERR_H
